 const posts = {
    one: {
        title: "8 Ways You Could Be Inviting a Cybersecurity Attack",
        para: "Businesses make decisions every day that negatively impact their security readiness: for example, refusing to shut down a server for proper patching or choosing to keep working on old hardware and software to save budget. These unreported decisions lead to a false sense of security and increase the likelihood and severity of an incident. You can’t buy your way out — no matter what you spend, you won’t be perfectly protected against cyberattacks. By trying to stop every risky activity, you will likely damage your organization’s ability to function. Accountability should mean that a decision to accept risk is defensible to key stakeholders. If accountability means that someone will get fired if something goes wrong, no one will engage. Organizations create generic high-level statements about their risk appetite that don’t support good decision making. Avoid promising to only engage in low-risk activities, as this can create invisible systemic risk. While this isn’t fair, it’s the result of decades of treating security as a black box. No one understands how it really works and as a result, when an incident does occur, the assumption is that someone must have made a mistake. We know of one company that even decided to move security under legal counsel so that discussions are privileged.",
        img: "media/post/1.jpg"
    },
    two: {
        title: "Develop a Security Strategy for Cyber-Physical Systems",
        para: "In early February, an unknown hacker remotely accessed a computer system at a water treatment plant in Florida and attempted to increase the amount of sodium hydroxide in the water supply to potentially dangerous levels. An operator noticed the intrusion, but the incident shows the potential for harm when the cyber and physical worlds intersect. These cyber-physical systems introduce a new set of risks that few security and risk leaders have had to consider. Although enterprise IT security is generally well-known and managed, cyber-physical systems challenge traditional security approaches. That’s because these systems process more than information; they manage and optimize physical outcomes, from individual processes to entire ecosystems. The term cyber-physical systems encompasses concepts such as IoT, smart city and systems created as a result of operational technology (OT) and IT convergence. By using the broader term, Gartner encourages security and risk leaders to think beyond IT security and develop security programs encompassing the entire spectrum of cyber-physical risk. Gartner predicts that by 2025, 50% of asset-intensive organizations such as utilities, resources and manufacturing firms will converge their cyber, physical and supply chain security teams under one chief security officer role that reports directly to the CEO. Plan for cyber-physical systems security: Start by documenting your organization’s business strategy, identifying the technology drivers and environmental trends that are unique to your enterprise, and mapping them to a broad view of cyber-physical risk. Use “voice of the business” language to lay out a vision statement that directly links the security and risk profiles of your organization’s cyber-physical systems to business outcomes.",
        img: "media/post/2.jpg"
    },
    three: {
        title: "The Top 8 Cybersecurity Predictions for 2021-2022",
        para: "The proliferation of cyber-physical systems — which includes systems that combine the cyber and physical worlds for technologies like autonomous cars or digital twins — represents yet another security risk for organizations, and how threat actors will target these systems is one of our top predictions for the coming years. Security and risk management has become a board-level issue for organizations. The number and sophistication of security breaches is rising, spurring increased legislation to protect consumers and putting security at the forefront of business decisions. 1. By the end of 2023, modern privacy laws will cover the personal information of 75% of the world’s population. 2. By 2024, organizations adopting a cybersecurity mesh architecture will reduce the financial impact of security incidents by an average of 90%. 3. By 2024, 30% of enterprises will adopt cloud-delivered Secure Web Gateway (SWG), Cloud Access Security Brokers (CASB), Zero Trust Network Access (ZTNA) and Firewall As A Service (FWaaS) capabilities from the same vendor. 4. By 2025, 60% of organizations will use cybersecurity risk as a primary determinant in conducting third-party transactions and business engagements. 5. The percentage of nation states passing legislation to regulate ransomware payments, fines and negotiations will rise to 30% by the end of 2025, compared to less than 1% in 2021. 6. By 2025, 40% of boards of directors will have a dedicated cybersecurity committee overseen by a qualified board member. 7. By 2025, 70% of CEOs will mandate a culture of organizational resilience to survive coincident threats from cybercrime, severe weather events, civil unrest and political instabilities. 8. By 2025, threat actors will have weaponized operational technology environments successfully enough to cause human casualties. ",
        img: "media/post/3.jpg"
    },
    four: {
        title: "4 Metrics That Prove Your Cybersecurity Program Works",
        para: "When an organization suffers a data breach or other cybersecurity incident, it is not judged by whether it had a low number of vulnerabilities or if it spent enough on security tools. The question is whether it did the right thing based on its budget, size and needs. Gartner predicts that within three years, 80% of the magnitude of fines imposed by regulators after a cybersecurity breach will be attributable to failures to prove the duty of due care was met rather than the impact of the breach. In the past, cybersecurity priorities and investments were largely based on doing something to avoid an outcome. For example, you might implement a patch management tool to avoid incidents resulting from unpatched security vulnerabilities. This is not the best course of action. Cybersecurity priorities and investments should be based on achieving a set of outcomes that are consistent, adequate, reasonable and effective (CARE). Gartner introduced CARE as a framework to help organizations assess the credibility and defensibility of their cybersecurity program. For example, rather than simply confirming the presence of tools and processes to patch vulnerabilities, an organization should measure outcomes directly related to the level of protection, such as the number of days it takes to update critical systems with critical patches. But because there is no industry standard set of security metrics or KPIs, every organization needs the flexibility to meet its unique circumstances. Consistency Metrics, Adequacy Metrics, Reasonableness metrics, and Effectiveness metrics.",
        img: "media/post/4.jpg"
    },
    five: {
        title: "Securing Cyber-Physical Systems",
        para: "In the United States, 16 sectors, including commercial facilities, communications, energy, financial services, and water and wastewater systems, have been deemed critical infrastructure. Other countries have identified similar sectors. Not only is each of these sectors critical to the proper functioning of modern societies, but they are also interdependent, and an attack on one can have a direct impact on others. In many countries, critical infrastructure is state-owned, while in others like the U.S., private industry owns and operates a much larger portion of it. No.1: By 2024, a cyberattack will so damage critical infrastructure that a member of the G20 will reciprocate with a declared physical attack. No. 2: By 2024, 80% of critical infrastructure organizations will abandon their existing siloed security solutions providers by adopting hyperconverged solutions to bridge cyber-physical and IT risks. No. 3: Through 2026, less than 30% of U.S. critical infrastructure owners and operators will meet newly mandated government security requirements for cyber-physical systems. The key is to develop a holistic, coordinated CPS security strategy while also incorporating into governance emerging security directives for critical infrastructure. The “National Security Memorandum on Improving Cybersecurity for Critical Infrastructure Control Systems,” for example, is prioritizing the electricity and natural gas pipeline sectors, followed by the water/wastewater and chemical sectors in the U.S.",
        img: "media/post/5.jpg"
    },

 };

 export default posts;